../tb/testbench_pipeline.sv
../rtl/ctrl/controller.sv
../rtl/ctrl/aludec.sv
../rtl/ctrl/maindec.sv
../rtl/ctrl/hazard.sv
../rtl/datapath/alu.sv
../rtl/datapath/adder.sv
../rtl/datapath/regfile.sv
../rtl/datapath/mux3.sv
../rtl/datapath/datapath.sv
../rtl/datapath/extend.sv
../rtl/datapath/mux2.sv
../rtl/dmem.sv
../rtl/riscv.sv
../rtl/top.sv
../rtl/imem.sv
../rtl/regs/flopr.sv
../rtl/regs/flopenrc.sv
../rtl/regs/floprc.sv
../rtl/regs/flopenr.sv
